[FIX] 예약 코드 리팩토링
sjkimplus/hi-clear pull request #17
Opened 2024-11-02 04:09 UTC by JH1Yoon

1. 튜터님께서 말씀하신 코드 리뷰 리팩토링
2. 중복된 코드 분리
3. 코드 컨벤션 맞추기(authUser.getEmail() -> authUser)
4. 성공 메시지를 enum을 통해 사

2024-11-02 04:45 UTC, taehyeokNam requested changes

2024-11-02 04:45 UTC, taehyeokNam commented on src/main/java/com/play/hiclear/domain/reservation/controller/ReservationController.java
> +    public ResponseEntity<String> delete(
크게 의미는 없지만
// 예약 취소 와 service 내부에서 실제로 호출한 cancelReservation(reservation); 처럼
controller와 service도 cancel로 맞춰주면 어떨까요!?

2024-11-02 04:45 UTC, taehyeokNam commented on src/main/java/com/play/hiclear/domain/reservation/dto/request/ReservationRequest.java
> +    @NotBlank
저는 Long 타입 경우 포스트맨으로 테스트 시 문제가 있었는데 문제가 없었나요?
저는 @NotBlank -> @NotNull 로 변경해주니 문제가 해결되었습니다.
알아보니 NotBlank는 String 타입에서 쓴다고 합니다!

2024-11-02 04:45 UTC, taehyeokNam commented on src/main/java/com/play/hiclear/domain/reservation/repository/ReservationRepository.java
> +
제가 QueryDSL을 잘 모르지만 Reservation도 소프트 딜리트로 알고있는데 DeletedAtIsNull은 없어도 되나요?

2024-11-02 04:45 UTC, taehyeokNam commented on src/main/java/com/play/hiclear/domain/reservation/controller/ReservationController.java
> +    public ResponseEntity<String> delete(
아니면 cancel로 할 시 cancelReservation과 혼동 때문에 그런걸까요?

2024-11-02 04:55 UTC, JH1Yoon commented on src/main/java/com/play/hiclear/domain/reservation/controller/ReservationController.java
> +    public ResponseEntity<String> delete(
음 예약 취소가 말 그대로 예약을 소프트 삭제를 하는 건데 저희가 전부 삭제는 delete로 맞추기로 해서 delete를 사용했는데 그러면 예약 취소를 예약삭제로 바꾸고, cancelReservation을 deleteReservation로 변경해도 괜찮을 것 같네요.

2024-11-02 06:31 UTC, taehyeokNam commented on src/main/java/com/play/hiclear/domain/reservation/controller/ReservationController.java
> +    public ResponseEntity<String> delete(
그것도 방법이네욥!

2024-11-03 09:07 UTC, KangDongJoon approved these changes

2024-11-03 14:29 UTC, sjkimplus approved these changes

2024-11-04 00:37 UTC, taehyeokNam approved these changes

2024-11-04 00:37 UTC, merged