[ADD] 번개 생성, 수정, 삭제
sjkimplus/hi-clear pull request #4
Opened 2024-10-25 08:56 UTC by sjkimplus

- 번개 생성, 수정, 삭제 구현
- Meeting 컨트롤러, 서비스, 리포 생성
- Participant 컨트롤러, 서비스, 리포 생성, 관련 enum생성

2024-10-25 09:10 UTC, KangDongJoon requested changes
GlobalExceptionHandler
String변수 삭제 필요 메세지 중복

2024-10-25 09:10 UTC, KangDongJoon commented on src/main/java/com/play/hiclear/common/exception/GlobalExceptionHandler.java
> +        String message = ex.getErrorCode().customMessage(ex.getMessage()); // detail 메시지도 보여줌
인수로 메세지를 받기때문에 메세지가 중복 출력될것으로 예상됩니다.
삭제해도될거같습니다.

2024-10-25 09:29 UTC, KUGOM requested changes
원활한 버전 관리를 위해서는 requestmapping에 버전을 넣으면 안될거같습니다.

2024-10-25 09:29 UTC, KUGOM commented on src/main/java/com/play/hiclear/domain/participant/controller/ParticipantController.java
> +@RequestMapping("/v1")
버전 관리를 위해 v1을 RequestMapping으로 두면 안될것 같습니다.

2024-10-25 09:46 UTC, KangDongJoon approved these changes
수정 코드 확인

2024-10-25 09:59 UTC, JH1Yoon approved these changes
나중에 merge하고서 conflict가 발생하면 수정하면 될 것 같아요!

2024-10-25 14:29 UTC, merged

2024-10-28 06:12 UTC, minahshin commented on src/main/java/com/play/hiclear/domain/meeting/controller/MeetingController.java
> +    @PostMapping("/v1/meetings")
겹치는 상위 url들은 @RequestMapping 이용하셔도 됩니다.

2024-10-28 06:12 UTC, minahshin commented on src/main/java/com/play/hiclear/domain/meeting/service/MeetingService.java
> +        return "번개 수정 성공";
성공 메시지도 별개의 enum에서 관리하여 이를 반환하셔도 좋습니다.(+http status code)

2024-10-28 06:12 UTC, minahshin commented on src/main/java/com/play/hiclear/domain/meeting/service/MeetingService.java
> +        meetingRepository.save(meeting);
Transactional이 있는 경우에는 entity의 변경 감지를 통해 commit 하므로, save를 작성하실 필요는 없습니다. 기존 코드에서 entity를 "수정" 할 때는 save를 지워주세요!

2024-10-28 06:12 UTC, minahshin commented on src/main/java/com/play/hiclear/domain/participant/service/ParticipantService.java
> +        User user = userRepository.findById(authUser.getUserId()).orElseThrow(() ->
자원이 없을 때의 모든 것을 자세히 알려줄 필요는 없습니다. 혹은 String 대신 class의 simpleName 메소드를 이용해보세요.