[FEAT] Reservation, Schedule 기능 구현
sjkimplus/hi-clear pull request #9
Opened 2024-10-29 08:15 UTC by JH1Yoon

- 예약
    - 사장님이 예약을 수락/거절 기능 구현
    - 예약 생성시 해당 코트의 사장님은 예약 생성 불가 및 코트 상태 확인
    - 해당 코트에 Timeslot을 생성하려는 건지 확인
    - 예약 취소시 예약이 이미 ACCEPTED이면 해당 예약이 현재 시간으로 24시간이내면 취소 불가
    - 
 - 모임일정
     - 동일한 Club에서 동일한 제목 일정 시작시간이 있으면 생성 불가능(하지만 삭제되었으면 가능)

2024-10-30 04:43 UTC, sjkimplus approved these changes

2024-10-30 04:43 UTC, sjkimplus commented on src/main/java/com/play/hiclear/domain/schedule/service/ScheduleService.java
> +            throw new CustomException(ErrorCode.NO_AUTHORITY, "모임일정");
getSimpleName 으로 바꿔주세요

2024-10-30 04:43 UTC, sjkimplus commented on src/main/java/com/play/hiclear/domain/schedule/service/ScheduleService.java
> +            throw new CustomException(ErrorCode.NO_AUTHORITY, "모임일정");
getSimpleName 으로 바꿔주세요

2024-10-30 04:43 UTC, sjkimplus commented on src/main/java/com/play/hiclear/domain/schedule/service/ScheduleService.java
>              throw new CustomException(ErrorCode.NO_AUTHORITY, "모임일정에");
getSimpleName 으로 바꿔주세요

2024-10-30 04:56 UTC, KangDongJoon requested changes
properties 수정바랍니다.

2024-10-30 04:56 UTC, KangDongJoon commented on src/main/java/com/play/hiclear/domain/reservation/entity/Reservation.java
> +    // 예약 수정 메서드(코트 시간)
update메서드가 여러개라 분리하기위함이면 해당 메서드도 updateTime이 더 일관성있지않을까요

2024-10-30 04:56 UTC, KangDongJoon commented on src/main/java/com/play/hiclear/domain/schedule/service/ScheduleService.java
> +        if (scheduleRequestDto.getStartTime() != null && scheduleRequestDto.getEndTime() != null) {
if를 중첩할필요없이 a && b && c로 처리가능하지않을까요?

2024-10-30 04:56 UTC, KangDongJoon commented on src/main/resources/application.properties
> +spring.datasource.username=root
환경변수를 사용하기로해서 다시 수정해주셔야할거같습니다.

2024-10-30 06:09 UTC, KangDongJoon approved these changes

2024-10-30 06:09 UTC, merged

2024-11-04 04:08 UTC, minahshin commented on src/main/java/com/play/hiclear/domain/reservation/controller/ReservationController.java
> +    public ResponseEntity<Map<String, Object>> change(
Map보다는 Dto를 사용하시는 것이 좋습니다.
하드코딩의 요소가 덜 들어가고, 오타에 대해 자유롭다는 것이 장점입니다.

2024-11-04 04:08 UTC, minahshin commented on src/main/java/com/play/hiclear/domain/reservation/entity/Reservation.java
> +@AllArgsConstructor
영속성으로 관리되는 id와 같은 칼럼이 있을때는 AllArgsConstructor를 지양해봅시다.

2024-11-04 04:08 UTC, minahshin commented on src/main/java/com/play/hiclear/domain/reservation/service/ReservationService.java
> +        LocalDate updatedDate = request.getDate() != null ? request.getDate() : reservation.getDate();
와이어프레임 상으로 한 화면에서 값들을 바꾼다면 patch보다는 put 매핑을 이용하여 null 체크에 대한 부담을 service 단에서 줄여보는 것이 좋습니다.
request dto에서 validation을 이용해보세요.